security:
  oauth2:
    client:
      clientId: <clientId>
      clientSecret: <clientSecret>
      accessTokenUri: https://login.microsoftonline.com/<tenantId>/oauth2/token
      userAuthorizationUri: https://login.microsoftonline.com/<tenantId>/oauth2/authorize
      clientAuthenticationScheme: form
      scope: openid
    resource:
      userInfoUri: https://graph.windows.net/me?api-version=1.6

server:
  port: 80

logging:
  level:
    org.springframework.security: DEBUG